version: "3"

services:
  haproxy:
    image: dockercloud/haproxy
    networks:
      - irohanet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
      - 1936:1936

networks:
  irohanet:
    external: true
